#!/bin/bash

# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause

PART_ROOT=$1
LABEL_PART_ROOTFS_ENC=$2
LABEL_DEV_ROOTFS_DEC=$3

set -e

echo "Guest OS installation script called with PART_ROOT=${PART_ROOT}, LABEL_PART_ROOTFS_ENC=${LABEL_PART_ROOTFS_ENC}, LABEL_DEV_ROOTFS_DEC=${LABEL_DEV_ROOTFS_DEC}"

## Install packages
apt update && apt install --yes --allow-downgrades shim-signed libtdx-attest-dev libtss2-dev

# Set mount information for partitions.
cat <<EOF >/etc/fstab
LABEL=${LABEL_PART_ROOTFS_ENC}    /               ext4   discard,errors=remount-ro       0 1
LABEL=boot          /boot           ext4   defaults                        0 1
LABEL=uefi          /boot/efi       vfat   umask=0077                      0 1
EOF

# Update the initial RAM filesystem (initramfs) for all installed kernels.
# In particular, this executes all the hooks in the folder initramfs/hooks.
update-initramfs -u -k all

# Generates new host keys for all key types that do not have host keys yet.
# This is important for ensuring secure SSH access to the system.
ssh-keygen -A
